//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("xKnightModel", "FK_XAttack_Attack", "Attack", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(xKnight.Models.Attack), "XAttack", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(xKnight.Models.XAttack), true)]
[assembly: EdmRelationshipAttribute("xKnightModel", "FK_Host_CrawlSetting", "CrawlSetting", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(xKnight.Models.CrawlSetting), "Host", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(xKnight.Models.Host), true)]
[assembly: EdmRelationshipAttribute("xKnightModel", "FK_Form_HostPage", "HostPage", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(xKnight.Models.HostPage), "Form", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(xKnight.Models.Form), true)]
[assembly: EdmRelationshipAttribute("xKnightModel", "FK_XAttack_Form", "Form", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(xKnight.Models.Form), "XAttack", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(xKnight.Models.XAttack), true)]
[assembly: EdmRelationshipAttribute("xKnightModel", "FK_HostPage_Host", "Host", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(xKnight.Models.Host), "HostPage", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(xKnight.Models.HostPage), true)]
[assembly: EdmRelationshipAttribute("xKnightModel", "FK_HostPage_HostPage", "HostPage", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(xKnight.Models.HostPage), "HostPage1", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(xKnight.Models.HostPage), true)]
[assembly: EdmRelationshipAttribute("xKnightModel", "AttackHost", "Attack", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(xKnight.Models.Attack), "Host", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(xKnight.Models.Host), true)]

#endregion

namespace xKnight.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class xKnightEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new xKnightEntities object using the connection string found in the 'xKnightEntities' section of the application configuration file.
        /// </summary>
        public xKnightEntities() : base("name=xKnightEntities", "xKnightEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new xKnightEntities object.
        /// </summary>
        public xKnightEntities(string connectionString) : base(connectionString, "xKnightEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new xKnightEntities object.
        /// </summary>
        public xKnightEntities(EntityConnection connection) : base(connection, "xKnightEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Attack> Attacks
        {
            get
            {
                if ((_Attacks == null))
                {
                    _Attacks = base.CreateObjectSet<Attack>("Attacks");
                }
                return _Attacks;
            }
        }
        private ObjectSet<Attack> _Attacks;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CrawlSetting> CrawlSettings
        {
            get
            {
                if ((_CrawlSettings == null))
                {
                    _CrawlSettings = base.CreateObjectSet<CrawlSetting>("CrawlSettings");
                }
                return _CrawlSettings;
            }
        }
        private ObjectSet<CrawlSetting> _CrawlSettings;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Form> Forms
        {
            get
            {
                if ((_Forms == null))
                {
                    _Forms = base.CreateObjectSet<Form>("Forms");
                }
                return _Forms;
            }
        }
        private ObjectSet<Form> _Forms;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Host> Hosts
        {
            get
            {
                if ((_Hosts == null))
                {
                    _Hosts = base.CreateObjectSet<Host>("Hosts");
                }
                return _Hosts;
            }
        }
        private ObjectSet<Host> _Hosts;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<HostPage> HostPages
        {
            get
            {
                if ((_HostPages == null))
                {
                    _HostPages = base.CreateObjectSet<HostPage>("HostPages");
                }
                return _HostPages;
            }
        }
        private ObjectSet<HostPage> _HostPages;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagram> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagram>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagram> _sysdiagrams;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<XAttack> XAttacks
        {
            get
            {
                if ((_XAttacks == null))
                {
                    _XAttacks = base.CreateObjectSet<XAttack>("XAttacks");
                }
                return _XAttacks;
            }
        }
        private ObjectSet<XAttack> _XAttacks;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Attacks EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAttacks(Attack attack)
        {
            base.AddObject("Attacks", attack);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CrawlSettings EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCrawlSettings(CrawlSetting crawlSetting)
        {
            base.AddObject("CrawlSettings", crawlSetting);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Forms EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToForms(Form form)
        {
            base.AddObject("Forms", form);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Hosts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToHosts(Host host)
        {
            base.AddObject("Hosts", host);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the HostPages EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToHostPages(HostPage hostPage)
        {
            base.AddObject("HostPages", hostPage);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagram sysdiagram)
        {
            base.AddObject("sysdiagrams", sysdiagram);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the XAttacks EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToXAttacks(XAttack xAttack)
        {
            base.AddObject("XAttacks", xAttack);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="xKnightModel", Name="Attack")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Attack : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Attack object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="attackType">Initial value of the AttackType property.</param>
        /// <param name="succeed">Initial value of the Succeed property.</param>
        /// <param name="hostId">Initial value of the HostId property.</param>
        public static Attack CreateAttack(global::System.Int32 id, global::System.String attackType, global::System.Boolean succeed, global::System.Int32 hostId)
        {
            Attack attack = new Attack();
            attack.Id = id;
            attack.AttackType = attackType;
            attack.Succeed = succeed;
            attack.HostId = hostId;
            return attack;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AttackType
        {
            get
            {
                return _AttackType;
            }
            set
            {
                OnAttackTypeChanging(value);
                ReportPropertyChanging("AttackType");
                _AttackType = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AttackType");
                OnAttackTypeChanged();
            }
        }
        private global::System.String _AttackType;
        partial void OnAttackTypeChanging(global::System.String value);
        partial void OnAttackTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String StartTime
        {
            get
            {
                return _StartTime;
            }
            set
            {
                OnStartTimeChanging(value);
                ReportPropertyChanging("StartTime");
                _StartTime = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("StartTime");
                OnStartTimeChanged();
            }
        }
        private global::System.String _StartTime;
        partial void OnStartTimeChanging(global::System.String value);
        partial void OnStartTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FinishTime
        {
            get
            {
                return _FinishTime;
            }
            set
            {
                OnFinishTimeChanging(value);
                ReportPropertyChanging("FinishTime");
                _FinishTime = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FinishTime");
                OnFinishTimeChanged();
            }
        }
        private global::System.String _FinishTime;
        partial void OnFinishTimeChanging(global::System.String value);
        partial void OnFinishTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Succeed
        {
            get
            {
                return _Succeed;
            }
            set
            {
                OnSucceedChanging(value);
                ReportPropertyChanging("Succeed");
                _Succeed = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Succeed");
                OnSucceedChanged();
            }
        }
        private global::System.Boolean _Succeed;
        partial void OnSucceedChanging(global::System.Boolean value);
        partial void OnSucceedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 HostId
        {
            get
            {
                return _HostId;
            }
            set
            {
                OnHostIdChanging(value);
                ReportPropertyChanging("HostId");
                _HostId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HostId");
                OnHostIdChanged();
            }
        }
        private global::System.Int32 _HostId;
        partial void OnHostIdChanging(global::System.Int32 value);
        partial void OnHostIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("xKnightModel", "FK_XAttack_Attack", "XAttack")]
        public EntityCollection<XAttack> XAttacks
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<XAttack>("xKnightModel.FK_XAttack_Attack", "XAttack");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<XAttack>("xKnightModel.FK_XAttack_Attack", "XAttack", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("xKnightModel", "AttackHost", "Host")]
        public Host Host
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Host>("xKnightModel.AttackHost", "Host").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Host>("xKnightModel.AttackHost", "Host").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Host> HostReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Host>("xKnightModel.AttackHost", "Host");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Host>("xKnightModel.AttackHost", "Host", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="xKnightModel", Name="CrawlSetting")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CrawlSetting : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CrawlSetting object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static CrawlSetting CreateCrawlSetting(global::System.Int32 id)
        {
            CrawlSetting crawlSetting = new CrawlSetting();
            crawlSetting.Id = id;
            return crawlSetting;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MaxPages
        {
            get
            {
                return _MaxPages;
            }
            set
            {
                OnMaxPagesChanging(value);
                ReportPropertyChanging("MaxPages");
                _MaxPages = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MaxPages");
                OnMaxPagesChanged();
            }
        }
        private Nullable<global::System.Int32> _MaxPages;
        partial void OnMaxPagesChanging(Nullable<global::System.Int32> value);
        partial void OnMaxPagesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MaxDepth
        {
            get
            {
                return _MaxDepth;
            }
            set
            {
                OnMaxDepthChanging(value);
                ReportPropertyChanging("MaxDepth");
                _MaxDepth = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MaxDepth");
                OnMaxDepthChanged();
            }
        }
        private Nullable<global::System.Int32> _MaxDepth;
        partial void OnMaxDepthChanging(Nullable<global::System.Int32> value);
        partial void OnMaxDepthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> MaxTime
        {
            get
            {
                return _MaxTime;
            }
            set
            {
                OnMaxTimeChanging(value);
                ReportPropertyChanging("MaxTime");
                _MaxTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MaxTime");
                OnMaxTimeChanged();
            }
        }
        private Nullable<global::System.Int64> _MaxTime;
        partial void OnMaxTimeChanging(Nullable<global::System.Int64> value);
        partial void OnMaxTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> MaxByte
        {
            get
            {
                return _MaxByte;
            }
            set
            {
                OnMaxByteChanging(value);
                ReportPropertyChanging("MaxByte");
                _MaxByte = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MaxByte");
                OnMaxByteChanged();
            }
        }
        private Nullable<global::System.Int64> _MaxByte;
        partial void OnMaxByteChanging(Nullable<global::System.Int64> value);
        partial void OnMaxByteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> StartTime
        {
            get
            {
                return _StartTime;
            }
            set
            {
                OnStartTimeChanging(value);
                ReportPropertyChanging("StartTime");
                _StartTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StartTime");
                OnStartTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _StartTime;
        partial void OnStartTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnStartTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FinishTime
        {
            get
            {
                return _FinishTime;
            }
            set
            {
                OnFinishTimeChanging(value);
                ReportPropertyChanging("FinishTime");
                _FinishTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FinishTime");
                OnFinishTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _FinishTime;
        partial void OnFinishTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnFinishTimeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("xKnightModel", "FK_Host_CrawlSetting", "Host")]
        public EntityCollection<Host> Hosts
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Host>("xKnightModel.FK_Host_CrawlSetting", "Host");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Host>("xKnightModel.FK_Host_CrawlSetting", "Host", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="xKnightModel", Name="Form")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Form : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Form object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="pageId">Initial value of the PageId property.</param>
        /// <param name="formContents">Initial value of the FormContents property.</param>
        /// <param name="action">Initial value of the Action property.</param>
        /// <param name="method">Initial value of the Method property.</param>
        public static Form CreateForm(global::System.Int32 id, global::System.Int32 pageId, global::System.String formContents, global::System.String action, global::System.String method)
        {
            Form form = new Form();
            form.Id = id;
            form.PageId = pageId;
            form.FormContents = formContents;
            form.Action = action;
            form.Method = method;
            return form;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PageId
        {
            get
            {
                return _PageId;
            }
            set
            {
                OnPageIdChanging(value);
                ReportPropertyChanging("PageId");
                _PageId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PageId");
                OnPageIdChanged();
            }
        }
        private global::System.Int32 _PageId;
        partial void OnPageIdChanging(global::System.Int32 value);
        partial void OnPageIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FormContents
        {
            get
            {
                return _FormContents;
            }
            set
            {
                OnFormContentsChanging(value);
                ReportPropertyChanging("FormContents");
                _FormContents = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FormContents");
                OnFormContentsChanged();
            }
        }
        private global::System.String _FormContents;
        partial void OnFormContentsChanging(global::System.String value);
        partial void OnFormContentsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Action
        {
            get
            {
                return _Action;
            }
            set
            {
                OnActionChanging(value);
                ReportPropertyChanging("Action");
                _Action = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Action");
                OnActionChanged();
            }
        }
        private global::System.String _Action;
        partial void OnActionChanging(global::System.String value);
        partial void OnActionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Method
        {
            get
            {
                return _Method;
            }
            set
            {
                OnMethodChanging(value);
                ReportPropertyChanging("Method");
                _Method = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Method");
                OnMethodChanged();
            }
        }
        private global::System.String _Method;
        partial void OnMethodChanging(global::System.String value);
        partial void OnMethodChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("xKnightModel", "FK_Form_HostPage", "HostPage")]
        public HostPage HostPage
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<HostPage>("xKnightModel.FK_Form_HostPage", "HostPage").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<HostPage>("xKnightModel.FK_Form_HostPage", "HostPage").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<HostPage> HostPageReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<HostPage>("xKnightModel.FK_Form_HostPage", "HostPage");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<HostPage>("xKnightModel.FK_Form_HostPage", "HostPage", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("xKnightModel", "FK_XAttack_Form", "XAttack")]
        public EntityCollection<XAttack> XAttacks
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<XAttack>("xKnightModel.FK_XAttack_Form", "XAttack");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<XAttack>("xKnightModel.FK_XAttack_Form", "XAttack", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="xKnightModel", Name="Host")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Host : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Host object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="crawlId">Initial value of the CrawlId property.</param>
        /// <param name="hostName">Initial value of the HostName property.</param>
        /// <param name="port">Initial value of the Port property.</param>
        /// <param name="status">Initial value of the Status property.</param>
        /// <param name="indexedPages">Initial value of the IndexedPages property.</param>
        /// <param name="time">Initial value of the Time property.</param>
        /// <param name="bytesDownloaded">Initial value of the BytesDownloaded property.</param>
        public static Host CreateHost(global::System.Int32 id, global::System.Int32 crawlId, global::System.String hostName, global::System.Int32 port, global::System.Int32 status, global::System.Int32 indexedPages, global::System.Int64 time, global::System.Int64 bytesDownloaded)
        {
            Host host = new Host();
            host.Id = id;
            host.CrawlId = crawlId;
            host.HostName = hostName;
            host.Port = port;
            host.Status = status;
            host.IndexedPages = indexedPages;
            host.Time = time;
            host.BytesDownloaded = bytesDownloaded;
            return host;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CrawlId
        {
            get
            {
                return _CrawlId;
            }
            set
            {
                OnCrawlIdChanging(value);
                ReportPropertyChanging("CrawlId");
                _CrawlId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CrawlId");
                OnCrawlIdChanged();
            }
        }
        private global::System.Int32 _CrawlId;
        partial void OnCrawlIdChanging(global::System.Int32 value);
        partial void OnCrawlIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String HostName
        {
            get
            {
                return _HostName;
            }
            set
            {
                OnHostNameChanging(value);
                ReportPropertyChanging("HostName");
                _HostName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("HostName");
                OnHostNameChanged();
            }
        }
        private global::System.String _HostName;
        partial void OnHostNameChanging(global::System.String value);
        partial void OnHostNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Port
        {
            get
            {
                return _Port;
            }
            set
            {
                OnPortChanging(value);
                ReportPropertyChanging("Port");
                _Port = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Port");
                OnPortChanged();
            }
        }
        private global::System.Int32 _Port;
        partial void OnPortChanging(global::System.Int32 value);
        partial void OnPortChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.Int32 _Status;
        partial void OnStatusChanging(global::System.Int32 value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastVisit
        {
            get
            {
                return _LastVisit;
            }
            set
            {
                OnLastVisitChanging(value);
                ReportPropertyChanging("LastVisit");
                _LastVisit = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastVisit");
                OnLastVisitChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastVisit;
        partial void OnLastVisitChanging(Nullable<global::System.DateTime> value);
        partial void OnLastVisitChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IndexedPages
        {
            get
            {
                return _IndexedPages;
            }
            set
            {
                OnIndexedPagesChanging(value);
                ReportPropertyChanging("IndexedPages");
                _IndexedPages = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IndexedPages");
                OnIndexedPagesChanged();
            }
        }
        private global::System.Int32 _IndexedPages;
        partial void OnIndexedPagesChanging(global::System.Int32 value);
        partial void OnIndexedPagesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Time
        {
            get
            {
                return _Time;
            }
            set
            {
                OnTimeChanging(value);
                ReportPropertyChanging("Time");
                _Time = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Time");
                OnTimeChanged();
            }
        }
        private global::System.Int64 _Time;
        partial void OnTimeChanging(global::System.Int64 value);
        partial void OnTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 BytesDownloaded
        {
            get
            {
                return _BytesDownloaded;
            }
            set
            {
                OnBytesDownloadedChanging(value);
                ReportPropertyChanging("BytesDownloaded");
                _BytesDownloaded = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BytesDownloaded");
                OnBytesDownloadedChanged();
            }
        }
        private global::System.Int64 _BytesDownloaded;
        partial void OnBytesDownloadedChanging(global::System.Int64 value);
        partial void OnBytesDownloadedChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("xKnightModel", "FK_Host_CrawlSetting", "CrawlSetting")]
        public CrawlSetting CrawlSetting
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CrawlSetting>("xKnightModel.FK_Host_CrawlSetting", "CrawlSetting").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CrawlSetting>("xKnightModel.FK_Host_CrawlSetting", "CrawlSetting").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CrawlSetting> CrawlSettingReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CrawlSetting>("xKnightModel.FK_Host_CrawlSetting", "CrawlSetting");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CrawlSetting>("xKnightModel.FK_Host_CrawlSetting", "CrawlSetting", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("xKnightModel", "FK_HostPage_Host", "HostPage")]
        public EntityCollection<HostPage> HostPages
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<HostPage>("xKnightModel.FK_HostPage_Host", "HostPage");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<HostPage>("xKnightModel.FK_HostPage_Host", "HostPage", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("xKnightModel", "AttackHost", "Attack")]
        public EntityCollection<Attack> Attacks
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Attack>("xKnightModel.AttackHost", "Attack");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Attack>("xKnightModel.AttackHost", "Attack", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="xKnightModel", Name="HostPage")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class HostPage : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new HostPage object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="hostId">Initial value of the HostId property.</param>
        /// <param name="url">Initial value of the Url property.</param>
        /// <param name="html">Initial value of the Html property.</param>
        /// <param name="depth">Initial value of the Depth property.</param>
        /// <param name="dateTime">Initial value of the DateTime property.</param>
        public static HostPage CreateHostPage(global::System.Int32 id, global::System.Int32 hostId, global::System.String url, global::System.String html, global::System.Int32 depth, global::System.DateTime dateTime)
        {
            HostPage hostPage = new HostPage();
            hostPage.Id = id;
            hostPage.HostId = hostId;
            hostPage.Url = url;
            hostPage.Html = html;
            hostPage.Depth = depth;
            hostPage.DateTime = dateTime;
            return hostPage;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 HostId
        {
            get
            {
                return _HostId;
            }
            set
            {
                OnHostIdChanging(value);
                ReportPropertyChanging("HostId");
                _HostId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HostId");
                OnHostIdChanged();
            }
        }
        private global::System.Int32 _HostId;
        partial void OnHostIdChanging(global::System.Int32 value);
        partial void OnHostIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Url
        {
            get
            {
                return _Url;
            }
            set
            {
                OnUrlChanging(value);
                ReportPropertyChanging("Url");
                _Url = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Url");
                OnUrlChanged();
            }
        }
        private global::System.String _Url;
        partial void OnUrlChanging(global::System.String value);
        partial void OnUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Html
        {
            get
            {
                return _Html;
            }
            set
            {
                OnHtmlChanging(value);
                ReportPropertyChanging("Html");
                _Html = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Html");
                OnHtmlChanged();
            }
        }
        private global::System.String _Html;
        partial void OnHtmlChanging(global::System.String value);
        partial void OnHtmlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Depth
        {
            get
            {
                return _Depth;
            }
            set
            {
                OnDepthChanging(value);
                ReportPropertyChanging("Depth");
                _Depth = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Depth");
                OnDepthChanged();
            }
        }
        private global::System.Int32 _Depth;
        partial void OnDepthChanging(global::System.Int32 value);
        partial void OnDepthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateTime
        {
            get
            {
                return _DateTime;
            }
            set
            {
                OnDateTimeChanging(value);
                ReportPropertyChanging("DateTime");
                _DateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateTime");
                OnDateTimeChanged();
            }
        }
        private global::System.DateTime _DateTime;
        partial void OnDateTimeChanging(global::System.DateTime value);
        partial void OnDateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> RefererId
        {
            get
            {
                return _RefererId;
            }
            set
            {
                OnRefererIdChanging(value);
                ReportPropertyChanging("RefererId");
                _RefererId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RefererId");
                OnRefererIdChanged();
            }
        }
        private Nullable<global::System.Int32> _RefererId;
        partial void OnRefererIdChanging(Nullable<global::System.Int32> value);
        partial void OnRefererIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("xKnightModel", "FK_Form_HostPage", "Form")]
        public EntityCollection<Form> Forms
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Form>("xKnightModel.FK_Form_HostPage", "Form");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Form>("xKnightModel.FK_Form_HostPage", "Form", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("xKnightModel", "FK_HostPage_Host", "Host")]
        public Host Host
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Host>("xKnightModel.FK_HostPage_Host", "Host").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Host>("xKnightModel.FK_HostPage_Host", "Host").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Host> HostReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Host>("xKnightModel.FK_HostPage_Host", "Host");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Host>("xKnightModel.FK_HostPage_Host", "Host", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("xKnightModel", "FK_HostPage_HostPage", "HostPage1")]
        public EntityCollection<HostPage> HostPage1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<HostPage>("xKnightModel.FK_HostPage_HostPage", "HostPage1");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<HostPage>("xKnightModel.FK_HostPage_HostPage", "HostPage1", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("xKnightModel", "FK_HostPage_HostPage", "HostPage")]
        public HostPage HostPage2
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<HostPage>("xKnightModel.FK_HostPage_HostPage", "HostPage").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<HostPage>("xKnightModel.FK_HostPage_HostPage", "HostPage").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<HostPage> HostPage2Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<HostPage>("xKnightModel.FK_HostPage_HostPage", "HostPage");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<HostPage>("xKnightModel.FK_HostPage_HostPage", "HostPage", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="xKnightModel", Name="sysdiagram")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagram : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagram object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagram Createsysdiagram(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagram sysdiagram = new sysdiagram();
            sysdiagram.name = name;
            sysdiagram.principal_id = principal_id;
            sysdiagram.diagram_id = diagram_id;
            return sysdiagram;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="xKnightModel", Name="XAttack")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class XAttack : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new XAttack object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="attackId">Initial value of the AttackId property.</param>
        /// <param name="formId">Initial value of the FormId property.</param>
        /// <param name="attackContent">Initial value of the AttackContent property.</param>
        /// <param name="responsePage">Initial value of the ResponsePage property.</param>
        /// <param name="xAttackType">Initial value of the xAttackType property.</param>
        public static XAttack CreateXAttack(global::System.Int32 id, global::System.Int32 attackId, global::System.Int32 formId, global::System.String attackContent, global::System.String responsePage, global::System.Int32 xAttackType)
        {
            XAttack xAttack = new XAttack();
            xAttack.Id = id;
            xAttack.AttackId = attackId;
            xAttack.FormId = formId;
            xAttack.AttackContent = attackContent;
            xAttack.ResponsePage = responsePage;
            xAttack.xAttackType = xAttackType;
            return xAttack;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AttackId
        {
            get
            {
                return _AttackId;
            }
            set
            {
                OnAttackIdChanging(value);
                ReportPropertyChanging("AttackId");
                _AttackId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AttackId");
                OnAttackIdChanged();
            }
        }
        private global::System.Int32 _AttackId;
        partial void OnAttackIdChanging(global::System.Int32 value);
        partial void OnAttackIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FormId
        {
            get
            {
                return _FormId;
            }
            set
            {
                OnFormIdChanging(value);
                ReportPropertyChanging("FormId");
                _FormId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FormId");
                OnFormIdChanged();
            }
        }
        private global::System.Int32 _FormId;
        partial void OnFormIdChanging(global::System.Int32 value);
        partial void OnFormIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AttackContent
        {
            get
            {
                return _AttackContent;
            }
            set
            {
                OnAttackContentChanging(value);
                ReportPropertyChanging("AttackContent");
                _AttackContent = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AttackContent");
                OnAttackContentChanged();
            }
        }
        private global::System.String _AttackContent;
        partial void OnAttackContentChanging(global::System.String value);
        partial void OnAttackContentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ResponsePage
        {
            get
            {
                return _ResponsePage;
            }
            set
            {
                OnResponsePageChanging(value);
                ReportPropertyChanging("ResponsePage");
                _ResponsePage = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ResponsePage");
                OnResponsePageChanged();
            }
        }
        private global::System.String _ResponsePage;
        partial void OnResponsePageChanging(global::System.String value);
        partial void OnResponsePageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 xAttackType
        {
            get
            {
                return _xAttackType;
            }
            set
            {
                OnxAttackTypeChanging(value);
                ReportPropertyChanging("xAttackType");
                _xAttackType = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("xAttackType");
                OnxAttackTypeChanged();
            }
        }
        private global::System.Int32 _xAttackType;
        partial void OnxAttackTypeChanging(global::System.Int32 value);
        partial void OnxAttackTypeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("xKnightModel", "FK_XAttack_Attack", "Attack")]
        public Attack Attack
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Attack>("xKnightModel.FK_XAttack_Attack", "Attack").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Attack>("xKnightModel.FK_XAttack_Attack", "Attack").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Attack> AttackReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Attack>("xKnightModel.FK_XAttack_Attack", "Attack");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Attack>("xKnightModel.FK_XAttack_Attack", "Attack", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("xKnightModel", "FK_XAttack_Form", "Form")]
        public Form Form
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Form>("xKnightModel.FK_XAttack_Form", "Form").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Form>("xKnightModel.FK_XAttack_Form", "Form").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Form> FormReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Form>("xKnightModel.FK_XAttack_Form", "Form");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Form>("xKnightModel.FK_XAttack_Form", "Form", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
