//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("xKnightModel", "FK_XAttack_Attack", "Attack", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(xKnight.Models.Attack), "XAttack", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(xKnight.Models.XAttack), true)]
[assembly: EdmRelationshipAttribute("xKnightModel", "FK_Host_CrawlSetting", "CrawlSetting", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(xKnight.Models.CrawlSetting), "Host", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(xKnight.Models.Host), true)]
[assembly: EdmRelationshipAttribute("xKnightModel", "FK_Form_HostPage", "HostPage", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(xKnight.Models.Webpage), "Form", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(xKnight.Models.Form), true)]
[assembly: EdmRelationshipAttribute("xKnightModel", "FK_XAttack_Form", "Form", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(xKnight.Models.Form), "XAttack", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(xKnight.Models.XAttack), true)]
[assembly: EdmRelationshipAttribute("xKnightModel", "FK_HostPage_Host", "Host", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(xKnight.Models.Host), "HostPage", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(xKnight.Models.Webpage), true)]
[assembly: EdmRelationshipAttribute("xKnightModel", "FK_HostPage_HostPage", "HostPage", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(xKnight.Models.Webpage), "HostPage1", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(xKnight.Models.Webpage), true)]
[assembly: EdmRelationshipAttribute("xKnightModel", "FormElementForm", "FormElement", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(xKnight.Models.FormElement), "Form", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(xKnight.Models.Form), true)]
[assembly: EdmRelationshipAttribute("xKnightModel", "AttackCrawlSetting", "Attack", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(xKnight.Models.Attack), "CrawlSetting", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(xKnight.Models.CrawlSetting), true)]
[assembly: EdmRelationshipAttribute("xKnightModel", "XAttackParamFormElement", "XAttackParam", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(xKnight.Models.XAttackParam), "FormElement", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(xKnight.Models.FormElement), true)]
[assembly: EdmRelationshipAttribute("xKnightModel", "XAttackParamXAttack", "XAttackParam", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(xKnight.Models.XAttackParam), "XAttack", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(xKnight.Models.XAttack), true)]

#endregion

namespace xKnight.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class xKnightEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new xKnightEntities object using the connection string found in the 'xKnightEntities' section of the application configuration file.
        /// </summary>
        public xKnightEntities() : base("name=xKnightEntities", "xKnightEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new xKnightEntities object.
        /// </summary>
        public xKnightEntities(string connectionString) : base(connectionString, "xKnightEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new xKnightEntities object.
        /// </summary>
        public xKnightEntities(EntityConnection connection) : base(connection, "xKnightEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Attack> Attacks
        {
            get
            {
                if ((_Attacks == null))
                {
                    _Attacks = base.CreateObjectSet<Attack>("Attacks");
                }
                return _Attacks;
            }
        }
        private ObjectSet<Attack> _Attacks;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CrawlSetting> CrawlSettings
        {
            get
            {
                if ((_CrawlSettings == null))
                {
                    _CrawlSettings = base.CreateObjectSet<CrawlSetting>("CrawlSettings");
                }
                return _CrawlSettings;
            }
        }
        private ObjectSet<CrawlSetting> _CrawlSettings;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Form> Forms
        {
            get
            {
                if ((_Forms == null))
                {
                    _Forms = base.CreateObjectSet<Form>("Forms");
                }
                return _Forms;
            }
        }
        private ObjectSet<Form> _Forms;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Host> Hosts
        {
            get
            {
                if ((_Hosts == null))
                {
                    _Hosts = base.CreateObjectSet<Host>("Hosts");
                }
                return _Hosts;
            }
        }
        private ObjectSet<Host> _Hosts;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Webpage> Webpages
        {
            get
            {
                if ((_Webpages == null))
                {
                    _Webpages = base.CreateObjectSet<Webpage>("Webpages");
                }
                return _Webpages;
            }
        }
        private ObjectSet<Webpage> _Webpages;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagram> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagram>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagram> _sysdiagrams;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<XAttack> XAttacks
        {
            get
            {
                if ((_XAttacks == null))
                {
                    _XAttacks = base.CreateObjectSet<XAttack>("XAttacks");
                }
                return _XAttacks;
            }
        }
        private ObjectSet<XAttack> _XAttacks;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<FormElement> FormElements
        {
            get
            {
                if ((_FormElements == null))
                {
                    _FormElements = base.CreateObjectSet<FormElement>("FormElements");
                }
                return _FormElements;
            }
        }
        private ObjectSet<FormElement> _FormElements;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<XAttackParam> XAttackParams
        {
            get
            {
                if ((_XAttackParams == null))
                {
                    _XAttackParams = base.CreateObjectSet<XAttackParam>("XAttackParams");
                }
                return _XAttackParams;
            }
        }
        private ObjectSet<XAttackParam> _XAttackParams;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Attacks EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAttacks(Attack attack)
        {
            base.AddObject("Attacks", attack);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CrawlSettings EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCrawlSettings(CrawlSetting crawlSetting)
        {
            base.AddObject("CrawlSettings", crawlSetting);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Forms EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToForms(Form form)
        {
            base.AddObject("Forms", form);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Hosts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToHosts(Host host)
        {
            base.AddObject("Hosts", host);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Webpages EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToWebpages(Webpage webpage)
        {
            base.AddObject("Webpages", webpage);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagram sysdiagram)
        {
            base.AddObject("sysdiagrams", sysdiagram);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the XAttacks EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToXAttacks(XAttack xAttack)
        {
            base.AddObject("XAttacks", xAttack);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the FormElements EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFormElements(FormElement formElement)
        {
            base.AddObject("FormElements", formElement);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the XAttackParams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToXAttackParams(XAttackParam xAttackParam)
        {
            base.AddObject("XAttackParams", xAttackParam);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="xKnightModel", Name="Attack")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Attack : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Attack object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="attackType">Initial value of the AttackType property.</param>
        /// <param name="hostId">Initial value of the HostId property.</param>
        /// <param name="crawlSettingId">Initial value of the CrawlSettingId property.</param>
        public static Attack CreateAttack(global::System.Int32 id, global::System.Int32 attackType, global::System.Int32 hostId, global::System.Int32 crawlSettingId)
        {
            Attack attack = new Attack();
            attack.Id = id;
            attack.AttackType = attackType;
            attack.HostId = hostId;
            attack.CrawlSettingId = crawlSettingId;
            return attack;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AttackType
        {
            get
            {
                return _AttackType;
            }
            set
            {
                OnAttackTypeChanging(value);
                ReportPropertyChanging("AttackType");
                _AttackType = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AttackType");
                OnAttackTypeChanged();
            }
        }
        private global::System.Int32 _AttackType;
        partial void OnAttackTypeChanging(global::System.Int32 value);
        partial void OnAttackTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> StartTime
        {
            get
            {
                return _StartTime;
            }
            set
            {
                OnStartTimeChanging(value);
                ReportPropertyChanging("StartTime");
                _StartTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StartTime");
                OnStartTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _StartTime;
        partial void OnStartTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnStartTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FinishTime
        {
            get
            {
                return _FinishTime;
            }
            set
            {
                OnFinishTimeChanging(value);
                ReportPropertyChanging("FinishTime");
                _FinishTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FinishTime");
                OnFinishTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _FinishTime;
        partial void OnFinishTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnFinishTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 HostId
        {
            get
            {
                return _HostId;
            }
            set
            {
                OnHostIdChanging(value);
                ReportPropertyChanging("HostId");
                _HostId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HostId");
                OnHostIdChanged();
            }
        }
        private global::System.Int32 _HostId;
        partial void OnHostIdChanging(global::System.Int32 value);
        partial void OnHostIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CrawlSettingId
        {
            get
            {
                return _CrawlSettingId;
            }
            set
            {
                OnCrawlSettingIdChanging(value);
                ReportPropertyChanging("CrawlSettingId");
                _CrawlSettingId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CrawlSettingId");
                OnCrawlSettingIdChanged();
            }
        }
        private global::System.Int32 _CrawlSettingId;
        partial void OnCrawlSettingIdChanging(global::System.Int32 value);
        partial void OnCrawlSettingIdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("xKnightModel", "FK_XAttack_Attack", "XAttack")]
        public EntityCollection<XAttack> XAttacks
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<XAttack>("xKnightModel.FK_XAttack_Attack", "XAttack");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<XAttack>("xKnightModel.FK_XAttack_Attack", "XAttack", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("xKnightModel", "AttackCrawlSetting", "CrawlSetting")]
        public CrawlSetting CrawlSetting
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CrawlSetting>("xKnightModel.AttackCrawlSetting", "CrawlSetting").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CrawlSetting>("xKnightModel.AttackCrawlSetting", "CrawlSetting").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CrawlSetting> CrawlSettingReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CrawlSetting>("xKnightModel.AttackCrawlSetting", "CrawlSetting");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CrawlSetting>("xKnightModel.AttackCrawlSetting", "CrawlSetting", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="xKnightModel", Name="CrawlSetting")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CrawlSetting : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CrawlSetting object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static CrawlSetting CreateCrawlSetting(global::System.Int32 id)
        {
            CrawlSetting crawlSetting = new CrawlSetting();
            crawlSetting.Id = id;
            return crawlSetting;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MaxPages
        {
            get
            {
                return _MaxPages;
            }
            set
            {
                OnMaxPagesChanging(value);
                ReportPropertyChanging("MaxPages");
                _MaxPages = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MaxPages");
                OnMaxPagesChanged();
            }
        }
        private Nullable<global::System.Int32> _MaxPages;
        partial void OnMaxPagesChanging(Nullable<global::System.Int32> value);
        partial void OnMaxPagesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MaxDepth
        {
            get
            {
                return _MaxDepth;
            }
            set
            {
                OnMaxDepthChanging(value);
                ReportPropertyChanging("MaxDepth");
                _MaxDepth = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MaxDepth");
                OnMaxDepthChanged();
            }
        }
        private Nullable<global::System.Int32> _MaxDepth;
        partial void OnMaxDepthChanging(Nullable<global::System.Int32> value);
        partial void OnMaxDepthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> MaxTime
        {
            get
            {
                return _MaxTime;
            }
            set
            {
                OnMaxTimeChanging(value);
                ReportPropertyChanging("MaxTime");
                _MaxTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MaxTime");
                OnMaxTimeChanged();
            }
        }
        private Nullable<global::System.Int64> _MaxTime;
        partial void OnMaxTimeChanging(Nullable<global::System.Int64> value);
        partial void OnMaxTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> MaxByte
        {
            get
            {
                return _MaxByte;
            }
            set
            {
                OnMaxByteChanging(value);
                ReportPropertyChanging("MaxByte");
                _MaxByte = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MaxByte");
                OnMaxByteChanged();
            }
        }
        private Nullable<global::System.Int64> _MaxByte;
        partial void OnMaxByteChanging(Nullable<global::System.Int64> value);
        partial void OnMaxByteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> StartTime
        {
            get
            {
                return _StartTime;
            }
            set
            {
                OnStartTimeChanging(value);
                ReportPropertyChanging("StartTime");
                _StartTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StartTime");
                OnStartTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _StartTime;
        partial void OnStartTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnStartTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FinishTime
        {
            get
            {
                return _FinishTime;
            }
            set
            {
                OnFinishTimeChanging(value);
                ReportPropertyChanging("FinishTime");
                _FinishTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FinishTime");
                OnFinishTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _FinishTime;
        partial void OnFinishTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnFinishTimeChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("xKnightModel", "FK_Host_CrawlSetting", "Host")]
        public EntityCollection<Host> Hosts
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Host>("xKnightModel.FK_Host_CrawlSetting", "Host");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Host>("xKnightModel.FK_Host_CrawlSetting", "Host", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("xKnightModel", "AttackCrawlSetting", "Attack")]
        public EntityCollection<Attack> Attacks
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Attack>("xKnightModel.AttackCrawlSetting", "Attack");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Attack>("xKnightModel.AttackCrawlSetting", "Attack", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="xKnightModel", Name="Form")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Form : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Form object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="webpageId">Initial value of the WebpageId property.</param>
        /// <param name="action">Initial value of the Action property.</param>
        /// <param name="method">Initial value of the Method property.</param>
        public static Form CreateForm(global::System.Int32 id, global::System.Int32 webpageId, global::System.String action, global::System.String method)
        {
            Form form = new Form();
            form.Id = id;
            form.WebpageId = webpageId;
            form.Action = action;
            form.Method = method;
            return form;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 WebpageId
        {
            get
            {
                return _WebpageId;
            }
            set
            {
                OnWebpageIdChanging(value);
                ReportPropertyChanging("WebpageId");
                _WebpageId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("WebpageId");
                OnWebpageIdChanged();
            }
        }
        private global::System.Int32 _WebpageId;
        partial void OnWebpageIdChanging(global::System.Int32 value);
        partial void OnWebpageIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Action
        {
            get
            {
                return _Action;
            }
            set
            {
                OnActionChanging(value);
                ReportPropertyChanging("Action");
                _Action = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Action");
                OnActionChanged();
            }
        }
        private global::System.String _Action;
        partial void OnActionChanging(global::System.String value);
        partial void OnActionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Method
        {
            get
            {
                return _Method;
            }
            set
            {
                OnMethodChanging(value);
                ReportPropertyChanging("Method");
                _Method = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Method");
                OnMethodChanged();
            }
        }
        private global::System.String _Method;
        partial void OnMethodChanging(global::System.String value);
        partial void OnMethodChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("xKnightModel", "FK_Form_HostPage", "HostPage")]
        public Webpage Webpage
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Webpage>("xKnightModel.FK_Form_HostPage", "HostPage").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Webpage>("xKnightModel.FK_Form_HostPage", "HostPage").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Webpage> WebpageReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Webpage>("xKnightModel.FK_Form_HostPage", "HostPage");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Webpage>("xKnightModel.FK_Form_HostPage", "HostPage", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("xKnightModel", "FK_XAttack_Form", "XAttack")]
        public EntityCollection<XAttack> XAttacks
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<XAttack>("xKnightModel.FK_XAttack_Form", "XAttack");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<XAttack>("xKnightModel.FK_XAttack_Form", "XAttack", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("xKnightModel", "FormElementForm", "FormElement")]
        public EntityCollection<FormElement> FormElements
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<FormElement>("xKnightModel.FormElementForm", "FormElement");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<FormElement>("xKnightModel.FormElementForm", "FormElement", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="xKnightModel", Name="FormElement")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FormElement : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new FormElement object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="formId">Initial value of the FormId property.</param>
        public static FormElement CreateFormElement(global::System.Int32 id, global::System.Int32 formId)
        {
            FormElement formElement = new FormElement();
            formElement.Id = id;
            formElement.FormId = formId;
            return formElement;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Value
        {
            get
            {
                return _Value;
            }
            set
            {
                OnValueChanging(value);
                ReportPropertyChanging("Value");
                _Value = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Value");
                OnValueChanged();
            }
        }
        private global::System.String _Value;
        partial void OnValueChanging(global::System.String value);
        partial void OnValueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private global::System.String _Type;
        partial void OnTypeChanging(global::System.String value);
        partial void OnTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FormId
        {
            get
            {
                return _FormId;
            }
            set
            {
                OnFormIdChanging(value);
                ReportPropertyChanging("FormId");
                _FormId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FormId");
                OnFormIdChanged();
            }
        }
        private global::System.Int32 _FormId;
        partial void OnFormIdChanging(global::System.Int32 value);
        partial void OnFormIdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("xKnightModel", "FormElementForm", "Form")]
        public Form Form
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Form>("xKnightModel.FormElementForm", "Form").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Form>("xKnightModel.FormElementForm", "Form").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Form> FormReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Form>("xKnightModel.FormElementForm", "Form");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Form>("xKnightModel.FormElementForm", "Form", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="xKnightModel", Name="Host")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Host : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Host object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="crawlId">Initial value of the CrawlId property.</param>
        /// <param name="hostName">Initial value of the HostName property.</param>
        /// <param name="indexedPages">Initial value of the IndexedPages property.</param>
        /// <param name="bytesDownloaded">Initial value of the BytesDownloaded property.</param>
        public static Host CreateHost(global::System.Int32 id, global::System.Int32 crawlId, global::System.String hostName, global::System.Int32 indexedPages, global::System.Int64 bytesDownloaded)
        {
            Host host = new Host();
            host.Id = id;
            host.CrawlId = crawlId;
            host.HostName = hostName;
            host.IndexedPages = indexedPages;
            host.BytesDownloaded = bytesDownloaded;
            return host;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CrawlId
        {
            get
            {
                return _CrawlId;
            }
            set
            {
                OnCrawlIdChanging(value);
                ReportPropertyChanging("CrawlId");
                _CrawlId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CrawlId");
                OnCrawlIdChanged();
            }
        }
        private global::System.Int32 _CrawlId;
        partial void OnCrawlIdChanging(global::System.Int32 value);
        partial void OnCrawlIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String HostName
        {
            get
            {
                return _HostName;
            }
            set
            {
                OnHostNameChanging(value);
                ReportPropertyChanging("HostName");
                _HostName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("HostName");
                OnHostNameChanged();
            }
        }
        private global::System.String _HostName;
        partial void OnHostNameChanging(global::System.String value);
        partial void OnHostNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IndexedPages
        {
            get
            {
                return _IndexedPages;
            }
            set
            {
                OnIndexedPagesChanging(value);
                ReportPropertyChanging("IndexedPages");
                _IndexedPages = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IndexedPages");
                OnIndexedPagesChanged();
            }
        }
        private global::System.Int32 _IndexedPages;
        partial void OnIndexedPagesChanging(global::System.Int32 value);
        partial void OnIndexedPagesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 BytesDownloaded
        {
            get
            {
                return _BytesDownloaded;
            }
            set
            {
                OnBytesDownloadedChanging(value);
                ReportPropertyChanging("BytesDownloaded");
                _BytesDownloaded = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BytesDownloaded");
                OnBytesDownloadedChanged();
            }
        }
        private global::System.Int64 _BytesDownloaded;
        partial void OnBytesDownloadedChanging(global::System.Int64 value);
        partial void OnBytesDownloadedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> StartTime
        {
            get
            {
                return _StartTime;
            }
            set
            {
                OnStartTimeChanging(value);
                ReportPropertyChanging("StartTime");
                _StartTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StartTime");
                OnStartTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _StartTime;
        partial void OnStartTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnStartTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FinishTime
        {
            get
            {
                return _FinishTime;
            }
            set
            {
                OnFinishTimeChanging(value);
                ReportPropertyChanging("FinishTime");
                _FinishTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FinishTime");
                OnFinishTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _FinishTime;
        partial void OnFinishTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnFinishTimeChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("xKnightModel", "FK_Host_CrawlSetting", "CrawlSetting")]
        public CrawlSetting CrawlSetting
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CrawlSetting>("xKnightModel.FK_Host_CrawlSetting", "CrawlSetting").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CrawlSetting>("xKnightModel.FK_Host_CrawlSetting", "CrawlSetting").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CrawlSetting> CrawlSettingReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CrawlSetting>("xKnightModel.FK_Host_CrawlSetting", "CrawlSetting");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CrawlSetting>("xKnightModel.FK_Host_CrawlSetting", "CrawlSetting", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("xKnightModel", "FK_HostPage_Host", "HostPage")]
        public EntityCollection<Webpage> HostPages
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Webpage>("xKnightModel.FK_HostPage_Host", "HostPage");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Webpage>("xKnightModel.FK_HostPage_Host", "HostPage", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="xKnightModel", Name="sysdiagram")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagram : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagram object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagram Createsysdiagram(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagram sysdiagram = new sysdiagram();
            sysdiagram.name = name;
            sysdiagram.principal_id = principal_id;
            sysdiagram.diagram_id = diagram_id;
            return sysdiagram;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="xKnightModel", Name="Webpage")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Webpage : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Webpage object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="hostId">Initial value of the HostId property.</param>
        /// <param name="url">Initial value of the Url property.</param>
        /// <param name="depth">Initial value of the Depth property.</param>
        /// <param name="dateTime">Initial value of the DateTime property.</param>
        public static Webpage CreateWebpage(global::System.Int32 id, global::System.Int32 hostId, global::System.String url, global::System.Int32 depth, global::System.DateTime dateTime)
        {
            Webpage webpage = new Webpage();
            webpage.Id = id;
            webpage.HostId = hostId;
            webpage.Url = url;
            webpage.Depth = depth;
            webpage.DateTime = dateTime;
            return webpage;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 HostId
        {
            get
            {
                return _HostId;
            }
            set
            {
                OnHostIdChanging(value);
                ReportPropertyChanging("HostId");
                _HostId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HostId");
                OnHostIdChanged();
            }
        }
        private global::System.Int32 _HostId;
        partial void OnHostIdChanging(global::System.Int32 value);
        partial void OnHostIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Url
        {
            get
            {
                return _Url;
            }
            set
            {
                OnUrlChanging(value);
                ReportPropertyChanging("Url");
                _Url = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Url");
                OnUrlChanged();
            }
        }
        private global::System.String _Url;
        partial void OnUrlChanging(global::System.String value);
        partial void OnUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Html
        {
            get
            {
                return _Html;
            }
            set
            {
                OnHtmlChanging(value);
                ReportPropertyChanging("Html");
                _Html = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Html");
                OnHtmlChanged();
            }
        }
        private global::System.String _Html;
        partial void OnHtmlChanging(global::System.String value);
        partial void OnHtmlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Depth
        {
            get
            {
                return _Depth;
            }
            set
            {
                OnDepthChanging(value);
                ReportPropertyChanging("Depth");
                _Depth = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Depth");
                OnDepthChanged();
            }
        }
        private global::System.Int32 _Depth;
        partial void OnDepthChanging(global::System.Int32 value);
        partial void OnDepthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateTime
        {
            get
            {
                return _DateTime;
            }
            set
            {
                OnDateTimeChanging(value);
                ReportPropertyChanging("DateTime");
                _DateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateTime");
                OnDateTimeChanged();
            }
        }
        private global::System.DateTime _DateTime;
        partial void OnDateTimeChanging(global::System.DateTime value);
        partial void OnDateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> RefererId
        {
            get
            {
                return _RefererId;
            }
            set
            {
                OnRefererIdChanging(value);
                ReportPropertyChanging("RefererId");
                _RefererId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RefererId");
                OnRefererIdChanged();
            }
        }
        private Nullable<global::System.Int32> _RefererId;
        partial void OnRefererIdChanging(Nullable<global::System.Int32> value);
        partial void OnRefererIdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("xKnightModel", "FK_Form_HostPage", "Form")]
        public EntityCollection<Form> Forms
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Form>("xKnightModel.FK_Form_HostPage", "Form");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Form>("xKnightModel.FK_Form_HostPage", "Form", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("xKnightModel", "FK_HostPage_Host", "Host")]
        public Host Host
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Host>("xKnightModel.FK_HostPage_Host", "Host").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Host>("xKnightModel.FK_HostPage_Host", "Host").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Host> HostReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Host>("xKnightModel.FK_HostPage_Host", "Host");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Host>("xKnightModel.FK_HostPage_Host", "Host", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("xKnightModel", "FK_HostPage_HostPage", "HostPage")]
        public Webpage Referer
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Webpage>("xKnightModel.FK_HostPage_HostPage", "HostPage").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Webpage>("xKnightModel.FK_HostPage_HostPage", "HostPage").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Webpage> RefererReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Webpage>("xKnightModel.FK_HostPage_HostPage", "HostPage");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Webpage>("xKnightModel.FK_HostPage_HostPage", "HostPage", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="xKnightModel", Name="XAttack")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class XAttack : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new XAttack object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="attackId">Initial value of the AttackId property.</param>
        /// <param name="formId">Initial value of the FormId property.</param>
        /// <param name="attackContent">Initial value of the AttackContent property.</param>
        /// <param name="responsePage">Initial value of the ResponsePage property.</param>
        public static XAttack CreateXAttack(global::System.Int32 id, global::System.Int32 attackId, global::System.Int32 formId, global::System.String attackContent, global::System.String responsePage)
        {
            XAttack xAttack = new XAttack();
            xAttack.Id = id;
            xAttack.AttackId = attackId;
            xAttack.FormId = formId;
            xAttack.AttackContent = attackContent;
            xAttack.ResponsePage = responsePage;
            return xAttack;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AttackId
        {
            get
            {
                return _AttackId;
            }
            set
            {
                OnAttackIdChanging(value);
                ReportPropertyChanging("AttackId");
                _AttackId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AttackId");
                OnAttackIdChanged();
            }
        }
        private global::System.Int32 _AttackId;
        partial void OnAttackIdChanging(global::System.Int32 value);
        partial void OnAttackIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FormId
        {
            get
            {
                return _FormId;
            }
            set
            {
                OnFormIdChanging(value);
                ReportPropertyChanging("FormId");
                _FormId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FormId");
                OnFormIdChanged();
            }
        }
        private global::System.Int32 _FormId;
        partial void OnFormIdChanging(global::System.Int32 value);
        partial void OnFormIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AttackContent
        {
            get
            {
                return _AttackContent;
            }
            set
            {
                OnAttackContentChanging(value);
                ReportPropertyChanging("AttackContent");
                _AttackContent = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AttackContent");
                OnAttackContentChanged();
            }
        }
        private global::System.String _AttackContent;
        partial void OnAttackContentChanging(global::System.String value);
        partial void OnAttackContentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ResponsePage
        {
            get
            {
                return _ResponsePage;
            }
            set
            {
                OnResponsePageChanging(value);
                ReportPropertyChanging("ResponsePage");
                _ResponsePage = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ResponsePage");
                OnResponsePageChanged();
            }
        }
        private global::System.String _ResponsePage;
        partial void OnResponsePageChanging(global::System.String value);
        partial void OnResponsePageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> StartTime
        {
            get
            {
                return _StartTime;
            }
            set
            {
                OnStartTimeChanging(value);
                ReportPropertyChanging("StartTime");
                _StartTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StartTime");
                OnStartTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _StartTime;
        partial void OnStartTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnStartTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FinishTime
        {
            get
            {
                return _FinishTime;
            }
            set
            {
                OnFinishTimeChanging(value);
                ReportPropertyChanging("FinishTime");
                _FinishTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FinishTime");
                OnFinishTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _FinishTime;
        partial void OnFinishTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnFinishTimeChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("xKnightModel", "FK_XAttack_Attack", "Attack")]
        public Attack Attack
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Attack>("xKnightModel.FK_XAttack_Attack", "Attack").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Attack>("xKnightModel.FK_XAttack_Attack", "Attack").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Attack> AttackReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Attack>("xKnightModel.FK_XAttack_Attack", "Attack");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Attack>("xKnightModel.FK_XAttack_Attack", "Attack", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("xKnightModel", "FK_XAttack_Form", "Form")]
        public Form Form
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Form>("xKnightModel.FK_XAttack_Form", "Form").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Form>("xKnightModel.FK_XAttack_Form", "Form").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Form> FormReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Form>("xKnightModel.FK_XAttack_Form", "Form");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Form>("xKnightModel.FK_XAttack_Form", "Form", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("xKnightModel", "XAttackParamXAttack", "XAttackParam")]
        public EntityCollection<XAttackParam> XAttackParams
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<XAttackParam>("xKnightModel.XAttackParamXAttack", "XAttackParam");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<XAttackParam>("xKnightModel.XAttackParamXAttack", "XAttackParam", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="xKnightModel", Name="XAttackParam")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class XAttackParam : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new XAttackParam object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="formElementId">Initial value of the FormElementId property.</param>
        /// <param name="xAttackId">Initial value of the XAttackId property.</param>
        public static XAttackParam CreateXAttackParam(global::System.Int32 id, global::System.Int32 formElementId, global::System.Int32 xAttackId)
        {
            XAttackParam xAttackParam = new XAttackParam();
            xAttackParam.Id = id;
            xAttackParam.FormElementId = formElementId;
            xAttackParam.XAttackId = xAttackId;
            return xAttackParam;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Value
        {
            get
            {
                return _Value;
            }
            set
            {
                OnValueChanging(value);
                ReportPropertyChanging("Value");
                _Value = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Value");
                OnValueChanged();
            }
        }
        private global::System.String _Value;
        partial void OnValueChanging(global::System.String value);
        partial void OnValueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FormElementId
        {
            get
            {
                return _FormElementId;
            }
            set
            {
                OnFormElementIdChanging(value);
                ReportPropertyChanging("FormElementId");
                _FormElementId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FormElementId");
                OnFormElementIdChanged();
            }
        }
        private global::System.Int32 _FormElementId;
        partial void OnFormElementIdChanging(global::System.Int32 value);
        partial void OnFormElementIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 XAttackId
        {
            get
            {
                return _XAttackId;
            }
            set
            {
                OnXAttackIdChanging(value);
                ReportPropertyChanging("XAttackId");
                _XAttackId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("XAttackId");
                OnXAttackIdChanged();
            }
        }
        private global::System.Int32 _XAttackId;
        partial void OnXAttackIdChanging(global::System.Int32 value);
        partial void OnXAttackIdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("xKnightModel", "XAttackParamFormElement", "FormElement")]
        public FormElement FormElement
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FormElement>("xKnightModel.XAttackParamFormElement", "FormElement").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FormElement>("xKnightModel.XAttackParamFormElement", "FormElement").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<FormElement> FormElementReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FormElement>("xKnightModel.XAttackParamFormElement", "FormElement");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<FormElement>("xKnightModel.XAttackParamFormElement", "FormElement", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("xKnightModel", "XAttackParamXAttack", "XAttack")]
        public XAttack XAttack
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<XAttack>("xKnightModel.XAttackParamXAttack", "XAttack").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<XAttack>("xKnightModel.XAttackParamXAttack", "XAttack").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<XAttack> XAttackReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<XAttack>("xKnightModel.XAttackParamXAttack", "XAttack");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<XAttack>("xKnightModel.XAttackParamXAttack", "XAttack", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
